theme: jekyll-theme-cayman

# Setup
title:        Panagiotis Gkrasis
tagline:      Android Developer | Athens, Greece
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Panagiotis Gkrasis
  url:        https://panosgr94.github.io/Portfolio/
