theme: jekyll-theme-cayman

# Setup
title:        Panagiotis Grassis
tagline:      Android Developer | Athens, Greece

# About/contact
author:
  name:       Panagiotis Grassis
  url:        https://panosgr94.github.io/Portfolio/
